(add-to-list 'load-path "~/.emacs.d/extensions/key-chord")
(require 'key-chord)
(key-chord-mode 1)

(key-chord-define-global "mx" 'smex)
(key-chord-define-global "fj" 'ido-switch-buffer)
(key-chord-define-global "xk" 'ido-kill-buffer)
(key-chord-define-global "xx" 'end-of-buffer)
(key-chord-define-global "xj" 'dired-jump)
(key-chord-define-global "js" 'save-buffer)
(key-chord-define-global "ww" 'beginning-of-buffer)
(key-chord-define-global "xf" 'ido-find-file)
(key-chord-define-global "xh" 'mark-whole-buffer)
(key-chord-define-global "cm" 'goto-match-paren)
(key-chord-define-global "xb" 'switch-to-buffer)
(key-chord-define-global "jj" 'er/expand-region)
(key-chord-define-global "kd" 'ace-jump-mode)
(key-chord-define-global "kc" 'ace-jump-char-mode)
(key-chord-define-global "kk" 'ace-jump-line-mode)
(key-chord-define dired-mode-map "oe" 'open-file-with-external-program)
(key-chord-define dired-mode-map "pv" 'play-video-file-with-vlc)
(key-chord-define dired-mode-map "ep" 'export-latex-to-pdf)

(provide 'init-key-chord)
