(add-to-list 'load-path "~/.emacs.d/extensions/evil")
(add-to-list 'load-path "~/.emacs.d/extensions/evil-surround")
(add-to-list 'load-path "~/.emacs.d/extensions/evil-nerd-commenter")
(require 'evil)
(require 'evil-surround)
(evil-mode t)
(global-evil-surround-mode 1)
(setq evilnc-hotkey-comment-operator ",,")
(require 'evil-nerd-commenter)
(evilnc-default-hotkeys)
(provide 'init-evil)