;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        comments-javadoc-return
        copy-line-or-region
        electric-pair-delete-pair
        evil-append
        evil-backward-char
        evil-backward-word-begin
        evil-change
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-digit-argument-or-evil-beginning-of-line
        evil-end-of-line
        evil-ex
        evil-exit-visual-state
        evil-find-char-to
        evil-force-normal-state
        evil-forward-char
        evil-forward-word-begin
        evil-forward-word-end
        evil-insert
        evil-next-line
        evil-normal-state
        evil-paste-after
        evil-previous-line
        evil-search-word-forward
        evil-shift-right
        goto-match-paren
        insert-couple-parentesis
        insert-semi-colon-with-ñ
        ispell-word
        keyboard-quit
        kill-region
        my-evil-force-normal-state
        nxml-electric-slash
        org-delete-char
        org-return-indent
        org-self-insert-command
        smex
        suspend-frame
        tinyeat-forward-preserve
        tinyeat-kill-line
        viper-backward-word
        viper-forward-word
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        evil-lookup
        evil-mouse-drag-region
        evil-window-middle
        ))
