(source gnu)
(source melpa)

(package "Emacs-setup" "0.1.0" "Carlo's personal Emacs setup.")

(depends-on "diff-hl")
(depends-on "highlight-symbol")
(depends-on "sass-mode")
(depends-on "multiple-cursors")
(depends-on "smex")
(depends-on "ido-complete-space-or-hyphen")
(depends-on "ido-vertical-mode")
(depends-on "expand-region")
(depends-on "markdown-mode")
(depends-on "evil-leader")
(depends-on "evil-nerd-commenter")
(depends-on "evil-numbers")
(depends-on "evil-surround")
(depends-on "php-mode")
