;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        end-of-buffer
        insert-semi-colon-with-ñ
        insert-single-parentesis
        mark-word
        org-beginning-of-line
        pabbrev-expand-maybe
        suspend-frame
        ))

(setq mc/cmds-to-run-once
      '(
        highlight-symbol-at-point
        ))
